name: CI/CD Pipeline for Docker

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Логин в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Сборка и пуш Docker-образа
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          yourdockerhubusername/your-image-name:latest

    # 4. Деплой на удаленный сервер через SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.5.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull yourdockerhubusername/your-image-name:latest
          docker-compose down && docker-compose up -d
